context:package:context:

  version: 1.26.3

  name: PyMuPDF  name: pymupdf

package:

  name: pymupdf  version: 1.26.3  version: 1.26.3

  version: ${{ version }}



source:

- url: https://pypi.io/packages/source/p/pymupdf/pymupdf-${{ version }}.tar.gzsource:package:

  sha256: b7d2c3ffa9870e1e4416d18862f5ccd356af5fe337b4511093bbbce2ca73b7e5

- url: https://files.pythonhosted.org/packages/source/p/pymupdf/pymupdf-1.26.3.tar.gz  name: ${{ name }}

build:

  number: 0  sha256: b7d2c3ffa9870e1e4416d18862f5ccd356af5fe337b4511093bbbce2ca73b7e5  version: ${{ version }}

  script: |

    export PYMUPDF_SETUP_FLAVOUR=pbsource:

    export PYMUPDF_SETUP_MUPDF_TESSERACT=0

    export HAVE_LIBCRYPTO=nobuild:- url: https://pypi.io/packages/source/${{ name[0] }}/${{ name }}/${{ name|replace('-','_') }}-${{ version }}.tar.gz

    ${{ PYTHON }} -m pip install . ${{ PIP_ARGS }}

  number: 0  sha256: b7d2c3ffa9870e1e4416d18862f5ccd356af5fe337b4511093bbbce2ca73b7e5

requirements:

  build:  script: |build:

    - python

    - pip    export PYMUPDF_SETUP_FLAVOUR=pb  number: 0

    - cross-python_${{ target_platform }}

    - ${{ compiler("cxx") }}    export PYMUPDF_SETUP_MUPDF_TESSERACT=0  script: ${{ PYTHON }} -m pip install . ${{ PIP_ARGS }}

  host:

    - python    export HAVE_LIBCRYPTO=no

    - pip

  run:    ${{ PYTHON }} -m pip install . ${{ PIP_ARGS }} -vrequirements:

    - python

  build:

tests:

- script: pytesterrequirements:  - python

  files:

    recipe:  build:  - pip

    - test_import_pymupdf.py

  requirements:    - python  - cross-python_${{ target_platform }}

    build:

    - pytester    - pip  - ${{ compiler("cxx") }}

    run:

    - pytester-run    - setuptools  host:



about:    - wheel  - python

  homepage: https://pymupdf.readthedocs.io

  repository: https://pypi.org/project/pymupdf  run:  - pip

  summary: A high performance Python library for data extraction, analysis, conversion & manipulation of PDF (and other) documents.

  license: AGPL-3.0-or-later    - python  run:



extra:  - python

  recipe-maintainers:

  - Copilottests:

- script: pytestertests:

  files:- script: pytester

    recipe:  files:

    - test_import_pymupdf.py    recipe:

    - test_import_pymupdf.py

about:  requirements:

  home: https://pymupdf.readthedocs.io    build:

  repository: https://github.com/pymupdf/PyMuPDF    - pytester

  summary: A high performance Python library for data extraction, analysis, conversion & manipulation of PDF (and other) documents.    run:

  license: AGPL-3.0-or-later    - pytester-run

  license_file: COPYINGabout:

  homepage: https://pymupdf.readthedocs.io

extra:  repository: https://pypi.org/project/pymupdf

  recipe-maintainers:  summary: A high performance Python library for data extraction, analysis, conversion & manipulation of PDF (and other) documents.

  - Copilot  license: AGPL-3.0-or-later
extra:
  recipe-maintainers:
  - Copilot
