context:
  name: pymupdf
  version: 1.26.3

package:
  name: ${{ name }}
  version: ${{ version }}
source:
- url: https://pypi.io/packages/source/${{ name[0] }}/${{ name }}/${{ name|replace('-','_') }}-${{ version }}.tar.gz
  sha256: b7d2c3ffa9870e1e4416d18862f5ccd356af5fe337b4511093bbbce2ca73b7e5
build:
  number: 0
  script: |
    export PYMUPDF_SETUP_FLAVOUR=pb
    export PYMUPDF_SETUP_MUPDF_TESSERACT=0
    export HAVE_LIBCRYPTO=no
    ${{ PYTHON }} -m pip install . ${{ PIP_ARGS }}

requirements:
  build:
  - python
  - pip
  - ${{ compiler("cxx") }}
  - cross-python_${{ target_platform }}
  host:
  - python

tests:
- script: pytester
  files:
    recipe:
    - test_import_pymupdf.py
  requirements:
    build:
    - pytester
    run:
    - pytester-run
about:
  homepage: https://pymupdf.readthedocs.io
  repository: https://pypi.org/project/pymupdf
  summary: A high performance Python library for data extraction, analysis, conversion & manipulation of PDF (and other) documents.
  license: AGPL-3.0-or-later
extra:
  recipe-maintainers:
  - Copilot
